development:
  cas_url: "https://idp-stg.login.iu.edu/idp/profile/cas/"
  filmdb_update_url: 'http://sycamore.dlib.indiana.edu:8527/services/update_batch/'

test:
  cas_url: "https://idp.login.iu.edu/idp/profile/cas"
  filmdb_update_url: 'http://sycamore.dlib.indiana.edu:8529/services/update_batch/'

production:
  cas_url: "https://idp.login.iu.edu/idp/profile/cas"
  filmdb_update_url: 'http://sycamore.dlib.indiana.edu:8528/services/update_batch/'

