class AddFieldsToFilmTms < ActiveRecord::Migration
  def change
    add_column :film_tms, :projection_print, :boolean
    add_column :film_tms, :a_roll, :boolean
    add_column :film_tms, :b_roll, :boolean
    add_column :film_tms, :c_roll, :boolean
    add_column :film_tms, :d_roll, :boolean
    add_column :film_tms, :answer_print, :boolean
    add_column :film_tms, :camera_original, :boolean
    add_column :film_tms, :composite, :boolean
    add_column :film_tms, :duplicate, :boolean
    add_column :film_tms, :edited, :boolean
    add_column :film_tms, :fine_grain_master, :boolean
    add_column :film_tms, :intermediate, :boolean
    add_column :film_tms, :kinescope, :boolean
    add_column :film_tms, :magnetic_track, :boolean
    add_column :film_tms, :master, :boolean
    add_column :film_tms, :mezzanine, :boolean
    add_column :film_tms, :negative, :boolean
    add_column :film_tms, :optical_sound_track, :boolean
    add_column :film_tms, :original, :boolean
    add_column :film_tms, :outs_and_trims, :boolean
    add_column :film_tms, :positive, :boolean
    add_column :film_tms, :reversal, :boolean
    add_column :film_tms, :work_print, :boolean
    add_column :film_tms, :separation_master, :boolean
    add_column :film_tms, :mixed_generation, :boolean
    add_column :film_tms, :original_camera, :boolean
    add_column :film_tms, :footage, :string
    add_column :film_tms, :acetate, :boolean
    add_column :film_tms, :polyester, :boolean
    add_column :film_tms, :nitrate, :boolean
    add_column :film_tms, :mixed, :boolean
    add_column :film_tms, :frame_rate, :string
    add_column :film_tms, :bw, :boolean
    add_column :film_tms, :toned, :boolean
    add_column :film_tms, :tinted, :boolean
    add_column :film_tms, :hand_coloring, :boolean
    add_column :film_tms, :stencil_coloring, :boolean
    add_column :film_tms, :color, :boolean
    add_column :film_tms, :ektachrome, :boolean
    add_column :film_tms, :kodachrome, :boolean
    add_column :film_tms, :technicolor, :boolean
    add_column :film_tms, :anscochrome, :boolean
    add_column :film_tms, :eco, :boolean
    add_column :film_tms, :eastman, :boolean
    add_column :film_tms, :aspect_ratio, :string
    add_column :film_tms, :one_point33, :boolean
    add_column :film_tms, :one_point37, :boolean
    add_column :film_tms, :one_point66, :boolean
    add_column :film_tms, :one_point85, :boolean
    add_column :film_tms, :two_point35, :boolean
    add_column :film_tms, :two_point39, :boolean
    add_column :film_tms, :two_point59, :boolean
    add_column :film_tms, :anamorphic, :boolean
    add_column :film_tms, :sound, :string
    add_column :film_tms, :optical, :boolean
    add_column :film_tms, :optical_variable_area, :boolean
    add_column :film_tms, :optical_variable_density, :boolean
    add_column :film_tms, :magnetic, :boolean
    add_column :film_tms, :digital_sdds, :boolean
    add_column :film_tms, :digital_dts, :boolean
    add_column :film_tms, :digital_dolby_digital, :boolean
    add_column :film_tms, :sound_on_separate_media, :boolean
    add_column :film_tms, :mixed_sound_format, :boolean
    add_column :film_tms, :clean, :string
    add_column :film_tms, :resolution, :string
    add_column :film_tms, :workflow, :string
    add_column :film_tms, :on_demand, :string
    add_column :film_tms, :return_on_original_reel, :string
    add_column :film_tms, :brittle, :string
    add_column :film_tms, :broken, :string
    add_column :film_tms, :channeling, :string
    add_column :film_tms, :color_fade, :string
    add_column :film_tms, :cue_marks, :string
    add_column :film_tms, :dirty, :string
    add_column :film_tms, :edge_damage, :string
    add_column :film_tms, :holes, :string
    add_column :film_tms, :peeling, :string
    add_column :film_tms, :perforation_damage, :string
    add_column :film_tms, :rusty, :string
    add_column :film_tms, :scratches, :string
    add_column :film_tms, :soundtrack_damage, :string
    add_column :film_tms, :splice_damage, :string
    add_column :film_tms, :stains, :string
    add_column :film_tms, :sticky, :string
    add_column :film_tms, :tape_residue, :string
    add_column :film_tms, :tearing, :string
    add_column :film_tms, :warp, :string
    add_column :film_tms, :water_damage, :string
    add_column :film_tms, :poor_wind, :boolean
    add_column :film_tms, :not_on_core_or_reel, :boolean
    add_column :film_tms, :lacquer_treated, :boolean
    add_column :film_tms, :replasticized, :boolean
    add_column :film_tms, :dusty, :boolean
    add_column :film_tms, :spoking, :boolean
    add_column :film_tms, :mold, :string
    add_column :film_tms, :shrinkage, :string
    add_column :film_tms, :ad_strip, :string
    add_column :film_tms, :missing_footage, :string
    add_column :film_tms, :miscellaneous, :string
    add_column :film_tms, :return_to, :string
    add_column :film_tms, :sound_mono, :boolean
    add_column :film_tms, :sound_stereo, :boolean
    add_column :film_tms, :sound_surround, :boolean
    add_column :film_tms, :sound_multi_track, :boolean
    add_column :film_tms, :sound_dual, :boolean
  end
end
