qc_user: qcProcess
qc_pass: processPassword
filmdb_user: filmdb_user
filmdb_pass: filmdb_pass
database:
  pool: 5
  host: pod_test_db_host
  port: 3306
  database: pod_test_database
  username: pod_test_db_username
  password: pod_test_db_password
  timeout: 2000
